language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb

after_script: "npm install codecov.io && cat ./coverage/lcov.info | codecov"